"""Issue drafting (Day 4-6). LLM-based structured output; no GitLab.

Evidence quotes are taken verbatim from the theme's real signals (not generated by the
model), so the drafted issue is grounded in actual customer reports. When existing
related issues were found by search_existing, they are surfaced to the model and carried
on the draft as `related_iids` for /relate linking at creation time.
"""

from __future__ import annotations

import logging
from typing import Literal

from pydantic import BaseModel

from tools.llm import generate_structured

_log = logging.getLogger("loopback")


def _humanize(text: str) -> str:
    """Strip the spaced em dash, the most common AI tell the model may still emit."""
    return (
        text.replace(" — ", ", ")
        .replace(" —", ",")
        .replace("— ", ", ")
        .replace("—", "-")
        .strip()
    )


class _Draft(BaseModel):
    title: str
    body: str
    repro_steps: list[str]
    suggested_labels: list[str]
    priority: Literal["critical", "high", "medium", "low"]
    remediation: str


def _prompt(
    label: str, severity: int, frequency: int, quotes: list[str], related: list[dict]
) -> str:
    quote_block = "\n".join(f"- {q}" for q in quotes)
    related_block = ""
    if related:
        refs = "\n".join(f"- #{r.get('iid')}: {r.get('title')}" for r in related)
        related_block = (
            "\nEXISTING POSSIBLY-RELATED ISSUES (reference these in the body if relevant):\n"
            f"{refs}\n"
        )
    return (
        "Draft a well-scoped GitLab issue for the engineering team based on this recurring "
        "customer-pain theme. Be concrete and technical; ground every claim in the reports "
        "and invent no facts.\n\n"
        "VOICE: write like a senior engineer filing the ticket: plain, direct, specific. "
        "Do NOT use em dashes; use periods or commas. Avoid marketing or filler words "
        "(seamless, robust, leverage, delve, elevate, streamline, unlock, game-changing). "
        "No 'not just X, but Y' constructions. Short, concrete sentences.\n\n"
        f"THEME: {label}\n"
        f"SEVERITY (1-5): {severity}\n"
        f"NUMBER OF REPORTS: {frequency}\n"
        f"REPRESENTATIVE CUSTOMER QUOTES:\n{quote_block}\n"
        f"{related_block}\n"
        "Produce:\n"
        "- title: a clear, specific issue title.\n"
        "- body: a 2-4 sentence problem statement grounded in the reports.\n"
        "- repro_steps: ordered steps to reproduce, inferred from the reports.\n"
        '- suggested_labels: 2-4 GitLab labels (e.g. "bug", "frontend", "priority::high").\n'
        "- priority: one of critical/high/medium/low, consistent with the severity.\n"
        "- remediation: a short suggested fix or investigation direction.\n"
    )


def draft_issues(themes: list, related: dict | None = None) -> dict:
    """Draft a structured GitLab issue for each theme. Does NOT touch GitLab.

    inputs: themes — ranked themes from cluster_and_rank; related — optional
            {theme_id: [{"iid","title"}, ...]} of existing issues found by search_existing.
    outputs: {"drafts": [{"theme_id","title","body","repro_steps":[...],
              "evidence_quotes":[...],"suggested_labels":[...],"priority","remediation",
              "related_iids":[...]}, ...]}
    side effects: one Gemini call per theme (network, billable). No GitLab.
    """
    related = related or {}
    drafts: list[dict] = []
    for theme in themes:
        quotes = theme.get("quotes", [])
        rel = related.get(theme["id"], [])
        try:
            d = generate_structured(
                _prompt(
                    theme["label"], theme.get("severity", 3), theme.get("frequency", 0), quotes, rel
                ),
                _Draft,
            )
        except Exception:  # noqa: BLE001 - one theme failing must not abort the whole batch
            _log.exception("drafting failed for theme %s; skipping it", theme.get("id"))
            continue
        drafts.append(
            {
                "theme_id": theme.get("id"),
                "title": _humanize(d.title),
                "body": _humanize(d.body),
                "repro_steps": [_humanize(s) for s in d.repro_steps],
                "evidence_quotes": quotes,  # real customer quotes, not model-generated
                "suggested_labels": d.suggested_labels,
                "priority": d.priority,
                "remediation": _humanize(d.remediation),
                "related_iids": [r["iid"] for r in rel if r.get("iid")],
                # ranking provenance, computed deterministically in clustering — carried so the
                # UI can show WHY this issue made the cut and where it ranks (not LLM-estimated).
                "frequency": theme.get("frequency", 0),
                "severity": theme.get("severity", 0),
                "score": theme.get("score", 0),
                "rank": theme.get("rank", 0),
                "channels": theme.get("channels", []),
            }
        )
    return {"drafts": drafts}
