"""Issue drafting (Day 4-6). LLM-based structured output; no GitLab.

Evidence quotes are taken verbatim from the theme's real signals (not generated by the
model), so the drafted issue is grounded in actual customer reports.
"""

from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

from tools.llm import generate_structured


class _Draft(BaseModel):
    title: str
    body: str
    repro_steps: list[str]
    suggested_labels: list[str]
    priority: Literal["critical", "high", "medium", "low"]
    remediation: str


def _prompt(label: str, severity: int, frequency: int, quotes: list[str]) -> str:
    quote_block = "\n".join(f"- {q}" for q in quotes)
    return (
        "Draft a well-scoped GitLab issue for the engineering team based on this recurring "
        "customer-pain theme. Be concrete and technical; ground every claim in the reports "
        "and invent no facts.\n\n"
        f"THEME: {label}\n"
        f"SEVERITY (1-5): {severity}\n"
        f"NUMBER OF REPORTS: {frequency}\n"
        f"REPRESENTATIVE CUSTOMER QUOTES:\n{quote_block}\n\n"
        "Produce:\n"
        "- title: a clear, specific issue title.\n"
        "- body: a 2-4 sentence problem statement grounded in the reports.\n"
        "- repro_steps: ordered steps to reproduce, inferred from the reports.\n"
        '- suggested_labels: 2-4 GitLab labels (e.g. "bug", "frontend", "priority::high").\n'
        "- priority: one of critical/high/medium/low, consistent with the severity.\n"
        "- remediation: a short suggested fix or investigation direction.\n"
    )


def draft_issues(themes: list, related: dict | None = None) -> dict:
    """Draft a structured GitLab issue for each theme. Does NOT touch GitLab.

    inputs: themes — ranked themes from cluster_and_rank; related — optional existing
            issues/MRs supplied by the agent at Day 7-9 (unused at this stage).
    outputs: {"drafts": [{"theme_id","title","body","repro_steps":[...],
              "evidence_quotes":[...],"suggested_labels":[...],"priority","remediation"}, ...]}
    side effects: one Gemini call per theme (network, billable). No GitLab.
    """
    drafts: list[dict] = []
    for theme in themes:
        quotes = theme.get("quotes", [])
        d = generate_structured(
            _prompt(theme["label"], theme.get("severity", 3), theme.get("frequency", 0), quotes),
            _Draft,
        )
        drafts.append(
            {
                "theme_id": theme.get("id"),
                "title": d.title.strip(),
                "body": d.body.strip(),
                "repro_steps": d.repro_steps,
                "evidence_quotes": quotes,  # real customer quotes, not model-generated
                "suggested_labels": d.suggested_labels,
                "priority": d.priority,
                "remediation": d.remediation.strip(),
            }
        )
    return {"drafts": drafts}
